export interface SoundEffect {
  id: string
  name: string
  keywords: string
  duration: number
  path: string
}

/** Original Zvid effects, generated by scripts/generate-sound-effects.mjs.
 * Versioned URLs keep audio already used in projects stable after updates. */
export const SOUND_EFFECTS: SoundEffect[] = [
  { id: 'click', name: 'Soft click', keywords: 'tap button interface', duration: 0.12 },
  { id: 'pop', name: 'Pop', keywords: 'bubble reveal playful', duration: 0.24 },
  { id: 'chime', name: 'Bright chime', keywords: 'bell ding sparkle', duration: 1.2 },
  { id: 'success', name: 'Success', keywords: 'complete positive achievement', duration: 0.95 },
  { id: 'notification', name: 'Notification', keywords: 'alert message ping', duration: 0.65 },
  { id: 'whoosh', name: 'Whoosh', keywords: 'swoosh transition swipe', duration: 0.75 },
  { id: 'riser', name: 'Rising sweep', keywords: 'transition build reveal', duration: 1.1 },
  { id: 'impact', name: 'Soft impact', keywords: 'hit thump drop bass', duration: 0.6 },
].map((effect) => ({ ...effect, path: `/audio/sound-effects/v1/${effect.id}.wav` }))

export function searchSoundEffects(query: string): SoundEffect[] {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean)
  return SOUND_EFFECTS.filter((effect) => {
    const haystack = `${effect.name} ${effect.keywords}`.toLowerCase()
    return terms.every((term) => haystack.includes(term))
  })
}
